-- DROP TABLE IF EXISTS TB_PACKAGE;
CREATE TABLE TB_PACKAGE (
	SEQ_NUM			INT 		NOT NULL PRIMARY KEY AUTO_INCREMENT
	, MAC_ADDRESS	VARCHAR(24)	NOT NULL
	, DATA			TEXT
	, CONSTRAINT TB_PACKAGE_UNIQUE1 UNIQUE (MAC_ADDRESS)
) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

INSERT INTO TB_PACKAGE(MAC_ADDRESS, DATA) VALUES ('11:11:11:11:11:11', 'TEST1');
INSERT INTO TB_PACKAGE(MAC_ADDRESS, DATA) VALUES ('22:22:22:22:22:22', 'TEST2');
